print('Roses are {color}')
print('{plural noun} are blue')
print('I love {celebrity}')
print('\n')
color = input('Roses are __  ')
plural_noun = input('__ are blue  ')
celebrity = input('I love __  ')
print('\n')
print(f'Roses are {color}')
print(f'{plural_noun} are blue')
print(f'I love {celebrity}')
